
services:
  snmp2mqtt:
    build: .
    container_name: snmptraps2mqtt
    environment:
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_TOPIC=snmp/traps
      - SNMP_PORT=162
      - SNMP_MIBS_TO_LOAD=INET-ADDRESS-MIB,NET-SNMP-MIB,RFC1213-MIB
    ports:
      - "162:162/udp"
    volumes:
      - ./mibs:/data/snmp_mibs
      #- ./compiled_mibs:/data/compiled_mibs
    restart: unless-stopped

